#!/bin/bash

#PBS -q dm
#PBS -N paraview
#PBS -l walltime=120:00:00
#PBS -l nodes=1:ncpus=7 
#PBS -l mem=64gb

# set path of working directory
 cd $PBS_O_WORKDIR

# Set number of threads
export OMP_NUM_THREADS=28

./viz > out.txt

