#!/bin/bash

#PBS -q dm
#PBS -N spheres
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ncpus=2 
#PBS -l mem=64gb

# set path of working directory
cd $PBS_O_WORKDIR

# Set number of threads
export OMP_NUM_THREADS=2 

./in3mg; 

