#!/bin/bash

#PBS -q dm
#PBS -N pardiso_MG    
#PBS -l walltime=120:00:00
#PBS -l nodes=1:ncpus=28
#PBS -l mem=64gb

# set path of working directory
cd $PBS_O_WORKDIR

# Set number of threads
export OMP_NUM_THREADS=28

./i3mg
